version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
#      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"