# Generated by Django 3.2.24 on 2024-02-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('rating_score', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
        ),
    ]
